---
name: Main_PAI_Advanced_Env
channels:
  - defaults
dependencies:
  - numpy=1.26.3
  - pandas=2.1.4
  - scikit-learn=1.1.2
  - seaborn=0.13.2
  - conda-forge::shap=0.45.1
  - conda-forge::xgboost=2.1.1
  - conda install anaconda::jinja2=3.1.4
